### ISSUE TITLE
QGFace

### ISSUE THREAD

**Issue by 1ggw1** [IsidoreSong/ContraFce#1]
作者大大，代码什么时候能上传呀

**Comment by 1ggw1** [comment]
adaface遇坑了，，想问一下QGFace代码什么时候才能上传，，，

**Comment by IsidoreSong** [comment]
我感觉纯人脸识别最近几年很难发了，我自己也要换方向了。这篇没有发出来，所以没放代码。
AdaFace的坑指的是什么？我可以单发代码给你
________________________________
发件人: 1ggw1 ***@***.***>
发送时间: 2024年1月18日 6:54
收件人: IsidoreSong/ContraFace ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [IsidoreSong/ContraFace] QGFace (Issue #1)


adaface遇坑了，，想问一下QGFace代码什么时候才能上传，，，

―

**Comment by 1ggw1** [comment]
可以的 谢谢作者大大～
guoguowen19980410@gmail.com

AdaFace虽然看起来召回率提升明显，但是用在大规模的人脸搜索中，模型会匹配到好多相似但不同的人脸。我自己做了一个测试，我先基于非公开数据集(图片质量有好有坏)+公开数据集训练一版模型(lfw准确率0.996)，再用vearch存储410万张人脸的embedding，进行人脸搜索时，相比insightface(arcface)的r50预训练模型，大于0.75的相似度阈值就可以判别为同一张人脸，Adaface在0.75-0.965阈值段有好多不同但相似的人脸被判别为同一个人，且占比较高，在0.965-0.99阈值段也有好多比较相似但不同的人脸被识别为同一个人，占比相对又少一些，在0.99阈值以上的人脸虽然基本是同一个人，但是对于非常模糊的图片，模型都把它识别为了同一个人。。。可能我的训练数据集里也有一些标签不同但是实际是同一个人的情况，但是不多，可即使这样，结果也有点出乎意料。

**Comment by IsidoreSong** [comment]
你做low-quality的话AdaFace确实可能不适合，就像我在QGFace中对它数据增强部分的实验一样。它的增强太狠了，图像的语义应该都碎了。
[QGFace](https://github.com/IsidoreSong/QGFace)的代码传了，你试一下会不会更好吧。估计config的部分你得看一会，我用hydra给重构了。
当时在TinyFace上测试Rank1结果不错，但是到了Rank5就不太行了。。。

你说特别模糊的情况，在QGFace里可以建一个模糊图片池，拿去做对比。
这代码有半年没跑了，但是从机器上拉下来的，应该没问题。后面如果有关于QGFace的问题我们就换一个仓库讨论吧。

**Comment by 1ggw1** [comment]
OK，谢谢作者大大～

**Comment by paopjian** [comment]
@1ggw1  我也在训练人脸识别模型, 我们在自采集数据集上发现adaface余弦相似度在 0.36 就很相似了, 你们相似度咋那么高? 还是说把[-1,1]范围压缩到[0,1]了? 
我们发现问题人脸相似用gradcam++看热力以后发现是一个中心圆, 怀疑是多人图等特征崩坏了

**Comment by IsidoreSong** [comment]
你的模型是多大的？如果用res18 的话，相似度应该上不去，res150的模型完全可以过拟合

**Comment by paopjian** [comment]
@IsidoreSong ir101的, 我们在cvlface库的基础上自采集数据+glint训练adaface, 但是余弦相似度这块数值比较低, 实际可用. 现在尝试用您的gqface移植过来看看, 就是训练速度上比adaface慢不少,

**Comment by 1ggw1** [comment]
一般训练几个epoch啊。我是训练的越久相似度越低，

paopjian ***@***.***> 于2026年7月14日周二 13:15写道：

**Comment by paopjian** [comment]
@1ggw1 5+15+5+15 四阶段训练, 分开训分类器和模型, 看来是这样了, 训了很久, 开源集数据没降低多少, 我们内部测试集成绩挺高

**Comment by IsidoreSong** [comment]
训练速度上比原装adaface慢是对的呀。因为我这个数据增强了以后，相当于用双倍数据做训练，正常来讲，比它要时间多一倍。

其实 18 年还是 19 年，有一篇论文介绍什么“devil in dataset”的，就讲人脸数据集里边他妈 40% 的错误都可能出现。所以你看后面 Microsoft 1M，它有 V2、V3 版，就是这个原因，大量数据它是有问题的。
训练几个epoch，我的论文还有adaface里边应该写得很清楚了。

如果你想看具体的余弦相似度，ArcFace 那一篇有介绍。我这一篇论文因为最后时间紧，可能没做这个实验；我的另一篇 CoreFace 是做了的，arXiv 上应该也能找到。我不确定你说的这个“低”到底是一个什么样的数值，因为如果人脸图片清晰度不够高，它就不可能很相似。
如果你想看完整版的话，我最后发在了 Pattern Recognition 上，里面有挺多实验的。

**Comment by 1ggw1** [comment]
你们是怎样采集人脸数据的呀，我这边的生产数据基本都是用户在手机端做活体，场景比较单一，每个identity大概50张图片，并做了去重+类内清洗，最终和glint360k组合，用组合数据做训练，效果总是比纯用glint360k要差很多，但是尝试过对生产的每个identity只取1～2张图片+和glint360k组合，效果相对会好一些

paopjian ***@***.***> 于2026年7月13日周一 16:02写道：

**Comment by paopjian** [comment]
@1ggw1 我们的数据比较恶心, 是街道数据, 还有证件照, 做了质量清洗+单匹配+聚类; glint也是有严重问题的, 我们重做了一遍align, 里面有大量多人图, 会导致图片特征失效, 下一步考虑对非中心人脸遮挡一下, 
手机活体照片应该非常优质啊, 只用一两图训练合理么, 应该看内部指标, 开源指标保证的是模型性能不下降太多就挺好的

**Comment by 1ggw1** [comment]
分析下来，手机拍摄的人脸，场景太单一了，或者说身份分类太简单了，这样的类别 图片多的话，降低了模型的泛化性

paopjian ***@***.***> 于2026年7月15日周三 16:40写道：

**Comment by 1ggw1** [comment]
为什么要重新做align，glint360k不是已经做过对齐吗，而且我问claude，说里面多人脸的占比并不少很高，

**Comment by paopjian** [comment]
@1ggw1  我们对glint重新做了人脸检测和align, 发现了下面问题
多人主体不明
<img width="1242" height="514" alt="Image" src="https://github.com/user-attachments/assets/9fc7c249-10a1-473d-85da-254df6bfd9ae" />
动漫 非人图等检测失败
<img width="2058" height="1318" alt="Image" src="https://github.com/user-attachments/assets/7189394f-1dfe-49ba-ba93-7d8a78bb1b1e" />
未按照arcface五点位置align, 模型特征热点变成中心圆
<img width="1786" height="1304" alt="Image" src="https://github.com/user-attachments/assets/f24bc76c-e0d1-492c-9607-fc311ed843ee" />
多人图还是需要想解决办法, 

<img width="2486" height="1084" alt="Image" src="https://github.com/user-attachments/assets/8a81bf70-9b85-4173-9409-9a26a7495a52" />

<img width="1280" height="1083" alt="Image" src="https://github.com/user-attachments/assets/8a8d1c94-b7f5-4b51-8614-8b580b7bf4ef" />

**Comment by 1ggw1** [comment]
占比大概多少，尝试过subcenter吗

paopjian ***@***.***> 于2026年7月15日周三 17:05写道：

**Comment by paopjian** [comment]
@1ggw1  学到了我们去研究下subcenter, 其实里面错误比例很低, 但还是尽量在优化数据
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta><byte-sheet-html-origin data-id="1784107604046" data-version="4" data-is-embed="false" data-grid-line-hidden="false" data-lark-html-role="root" data-importRangeRawData-spreadSource="https://lwf64uddzps.feishu.cn/wiki/RUWlw3ysWiaHMbkM9VRc9doJnlc" data-importRangeRawData-range="&#39;私有数据集&#39;!A42:J48">
glint采样 | 6,820,523图片 | 56,000组 |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
模型名 | TPIR@FPIR=1e-4 | TPIR@FPIR=1e-5 | TPIR@FPIR=1e-6 | TPIR@FPIR=1e-7 | TPIR@FPIR=1e-8 | TPIR@FPIR=1e-9 | TPIR@FPIR=1e-10 | TPIR@FPIR=1e-11 | TPIR@FPIR=1e-12
adaface | 99.52 | 98.71 | 96.98 | 93.81 | 88.64 | 75.21 | 29.76 | 7.02 | 1.91
训练模型| 99.44 | 98.38 | 96.19 | 92.41 | 86.64 | 74.91 | 20.57 | 0.85 | 0.37

</byte-sheet-html-origin>

**Comment by 1ggw1** [comment]
你们有WebFace42M/WebFace260M的数据集网盘地址吗，需要做一些验证，，，

**Comment by paopjian** [comment]
@1ggw1 没有, 官网打不开了, 他们估计摆烂不管了
